//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TextResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Guesses (rank = 1).
        /// </summary>
        internal static string StatType_CorrectGuessesRank1 {
            get {
                return ResourceManager.GetString("StatType_CorrectGuessesRank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped Games.
        /// </summary>
        internal static string StatType_DroppedGames {
            get {
                return ResourceManager.GetString("StatType_DroppedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Guesses.
        /// </summary>
        internal static string StatType_FailedGuesses {
            get {
                return ResourceManager.GetString("StatType_FailedGuesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        internal static string StatType_GamesPlayed {
            get {
                return ResourceManager.GetString("StatType_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games resulting in new Objects.
        /// </summary>
        internal static string StatType_GamesResultingInNewObject {
            get {
                return ResourceManager.GetString("StatType_GamesResultingInNewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses with rank in [2, 10].
        /// </summary>
        internal static string StatType_GuessesRank210 {
            get {
                return ResourceManager.GetString("StatType_GuessesRank210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses with rank &gt; 10.
        /// </summary>
        internal static string StatType_GuessesRankOver10 {
            get {
                return ResourceManager.GetString("StatType_GuessesRankOver10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Factor.
        /// </summary>
        internal static string StatType_KnowledgeFactor {
            get {
                return ResourceManager.GetString("StatType_KnowledgeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Objects.
        /// </summary>
        internal static string StatType_NumberOfObjects {
            get {
                return ResourceManager.GetString("StatType_NumberOfObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Questions.
        /// </summary>
        internal static string StatType_NumberOfQuestions {
            get {
                return ResourceManager.GetString("StatType_NumberOfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premature Guesses.
        /// </summary>
        internal static string StatType_PrematureGuesses {
            get {
                return ResourceManager.GetString("StatType_PrematureGuesses", resourceCulture);
            }
        }
    }
}
